-- ============================================================
-- weather-etl database schema
-- ============================================================
-- Three tables:
--   locations : one row per location (dimension table)
--   readings  : forecast readings (references locations)
--   actuals   : observed/historical readings (references locations)
--
-- Order matters: locations must be created FIRST, because both
-- readings and actuals have foreign keys referencing it.
--
-- Key design notes:
--   * location_id is a surrogate key generated by the database.
--   * UNIQUE (latitude, longitude) prevents duplicate locations
--     and enables upserts (ON CONFLICT) for idempotency.
--   * readings are uniquely identified by (location_id, time,
--     forecast_issued) -- the same target hour can be forecast on
--     multiple issue dates, so all three columns are needed.
--   * actuals are uniquely identified by (location_id, time) --
--     observed reality happens once per hour, so no issue date.
--   * Forecast precipitation is a PROBABILITY (integer %); actual
--     precipitation is an AMOUNT (double, mm). Different measure,
--     different column name and type -- the forecast/actual asymmetry.
-- ============================================================


-- ------------------------------------------------------------
-- locations (create first -- others reference it)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS locations (
    location_id        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    latitude           DOUBLE PRECISION NOT NULL,
    longitude          DOUBLE PRECISION NOT NULL,
    elevation          DOUBLE PRECISION,
    timezone           TEXT,
    utc_offset_seconds INTEGER,
    unit_time          TEXT,
    unit_temp          TEXT,
    UNIQUE (latitude, longitude)
);


-- ------------------------------------------------------------
-- readings (forecast data)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS readings (
    reading_id                INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    location_id               INT NOT NULL REFERENCES locations(location_id),
    forecast_issued           TIMESTAMPTZ NOT NULL,
    time                      TIMESTAMP NOT NULL,
    temperature_2m            DOUBLE PRECISION,
    precipitation_probability INTEGER,
    UNIQUE (location_id, time, forecast_issued)
);


-- ------------------------------------------------------------
-- actuals (observed / historical data)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS actuals (
    reading_id     INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    location_id    INT NOT NULL REFERENCES locations(location_id),
    time           TIMESTAMP NOT NULL,
    temperature_2m DOUBLE PRECISION,
    precipitation  DOUBLE PRECISION,
    UNIQUE (location_id, time)
);

-- ------------------------------------------------------------
-- forecast_accuracy (view: compares forecasts to actuals)
-- ------------------------------------------------------------
CREATE VIEW forecast_accuracy AS
SELECT
    readings.time,
    readings.temperature_2m AS forecast_temp,
    actuals.temperature_2m AS actual_temp,
    readings.temperature_2m - actuals.temperature_2m AS temp_error
FROM readings
JOIN actuals
    ON readings.location_id = actuals.location_id
    AND readings.time = actuals.time;